name: build

on:
  push:
    paths:
      - 'osu.Game.Rulesets.Space/**'
  pull_request:
    paths:
      - 'osu.Game.Rulesets.Space/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore osu.Game.Rulesets.Space.sln

      - name: Build
        run: dotnet build osu.Game.Rulesets.Space.sln --configuration Release --no-restore

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: osu.Game.Rulesets.Space
          path: |
            osu.Game.Rulesets.Space/bin/Release/**/*.dll
            osu.Game.Rulesets.Space/bin/Release/**/*.pdb